apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: web-gateway
spec:
  # クラスタ内の GatewayClass "nginx" を参照
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: nginx-gateway.local
      allowedRoutes:
        namespaces:
          from: Same
