apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # このディレクトリ内で適用対象に含めるリソース定義ファイルを参照
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - httproute.yaml
